export const CREATE_CARTS_REQUEST = "CREATE_CARTS_REQUEST";
export const CREATE_CARTS_SUCCESS = "CREATE_CARTS_SUCCESS";
export const CREATE_CARTS_RESET = "CREATE_CARTS_RESET";
export const CREATE_CARTS_ERROR = "CREATE_CARTS_ERROR";

export const GET_CARTS_REQUEST = "GET_CARTS_REQUEST";
export const GET_CARTS_SUCCESS = "GET_CARTS_SUCCESS";
export const GET_CARTS_RESET = "GET_CARTS_RESET";
export const GET_CARTS_ERROR = "GET_CARTS_ERROR";

export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_RESET = "GET_CART_RESET";
export const GET_CART_ERROR = "GET_CART_ERROR";

export const UPDATE_CARTS_REQUEST = "UPDATE_CARTS_REQUEST";
export const UPDATE_CARTS_SUCCESS = "UPDATE_CARTS_SUCCESS";
export const UPDATE_CARTS_RESET = "UPDATE_CARTS_RESET";
export const UPDATE_CARTS_ERROR = "UPDATE_CARTS_ERROR";

export const DELETE_CARTS_REQUEST = "DELETE_CARTS_REQUEST";
export const DELETE_CARTS_SUCCESS = "DELETE_CARTS_SUCCESS";
export const DELETE_CARTS_RESET = "DELETE_CARTS_RESET";
export const DELETE_CARTS_ERROR = "DELETE_CARTS_ERROR";
