export const CREATE_FAVORITE_REQUEST = "CREATE_FAVORITE_REQUEST";
export const CREATE_FAVORITE_SUCCESS = "CREATE_FAVORITE_SUCCESS";
export const CREATE_FAVORITE_RESET = "CREATE_FAVORITE_RESET";
export const CREATE_FAVORITE_ERROR = "CREATE_FAVORITE_ERROR";

export const GET_FAVORITES_REQUEST = "GET_FAVORITES_REQUEST";
export const GET_FAVORITES_SUCCESS = "GET_FAVORITES_SUCCESS";
export const GET_FAVORITES_RESET = "GET_FAVORITES_RESET";
export const GET_FAVORITES_ERROR = "GET_FAVORITES_ERROR";

export const GET_FAVORITE_REQUEST = "GET_FAVORITE_REQUEST";
export const GET_FAVORITE_SUCCESS = "GET_FAVORITE_SUCCESS";
export const GET_FAVORITE_RESET = "GET_FAVORITE_RESET";
export const GET_FAVORITE_ERROR = "GET_FAVORITE_ERROR";

export const DELETE_FAVORITE_REQUEST = "DELETE_FAVORITE_REQUEST";
export const DELETE_FAVORITE_SUCCESS = "DELETE_FAVORITE_SUCCESS";
export const DELETE_FAVORITE_RESET = "DELETE_FAVORITE_RESET";
export const DELETE_FAVORITE_ERROR = "DELETE_FAVORITE_ERROR";
