export const  CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const  CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const  CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET"
export const  CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR"



export const  GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
export const  GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const  GET_PRODUCT_RESET = "GET_PRODUCT_RESET"
export const  GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR"


export const  GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const  GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const  GET_PRODUCTS_RESET = "GET_PRODUCTS_RESET"
export const  GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"



export const  UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const  UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const  UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET"
export const  UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR"


export const  DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const  DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const  DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET"
export const  DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR"